version: '3.9'

services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - nads_net

  postgres:
    image: postgres:16-alpine
    container_name: nads_postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nads}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nadspassword}
      POSTGRES_DB: ${POSTGRES_DB:-nads_db}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nads}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - nads_net

  influxdb:
    image: influxdb:2.7-alpine
    container_name: nads_influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-adminpassword}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-nads}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-network_traffic}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:-mydevtoken}

    volumes:
      - influxdb_data:/var/lib/influxdb2

    healthcheck:
      test: [ "CMD", "influx", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    networks:
      - nads_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"

    environment:
      REDIS_URL: redis://redis:6379
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN:-nads}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:-network_traffic}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-nads}:${POSTGRES_PASSWORD:-nadspassword}@postgres:5432/${POSTGRES_DB:-nads_db}
      SECRET_KEY: ${SECRET_KEY:-changeme_in_production}

    volumes:
      - ./ml/models:/app/models:ro

    depends_on:
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      postgres:
        condition: service_healthy

    networks:
      - nads_net

networks:
  nads_net:


volumes:
  influxdb_data:
